esphome:
  name: espcam

esp32:
  board: esp32dev

status_led:
  pin: 33

esp32_camera:
  id: espcam
  name: esp-cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 640x480
  on_image:
    then:
      - light.turn_on: cam_flash
      - delay: 1s
      - light.turn_off: cam_flash
  idle_framerate: 0 fps

output:
  - platform: ledc
    pin: GPIO4
    id: espcam_led

light:
  - platform: binary
    output: espcam_led
    id: cam_flash
    name: "Camera flash"

# http server setting
esp32_camera_web_server:
  # - port: 8080
  #   mode: stream
  - port: 8081
    mode: snapshot

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# run webserver
web_server:
  port: 80
  local: true

ota:
  platform: esphome
  password: !secret ota_password

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address
