esphome:
  name: pico4

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

api:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

## MHZ19 setup
# uart:
#   tx_pin: 0
#   rx_pin: 1
#   baud_rate: 9600
# sensor:
#   - platform: mhz19
#     co2:
#       name: MH-Z19 CO2 Value
#     temperature:
#       name: MH-Z19 Temperature

i2c:
  - id: bus0
    sda: 0
    scl: 1
  - id: bus1
    sda: 26
    scl: 27

sensor:
  - platform: scd30
    i2c_id: bus0
    co2:
      name: "Desk CO2"
      accuracy_decimals: 1
    temperature:
      name: "Desk Temperature"
      accuracy_decimals: 2
    humidity:
      name: "Desk Humidity"
      accuracy_decimals: 1
    address: 0x61
    update_interval: 2s
  - platform: bme280_i2c
    i2c_id: bus1
    temperature:
      name: "Desk BME280 Temperature"
    pressure:
      name: "Desk BME280 Pressure"
    humidity:
      name: "Desk BME280 Humidity"
    address: 0x76
    update_interval: 30s

ota:
  platform: esphome
  password: !secret ota_password

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
