esphome:
  name: pico7

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

api:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600

# activate GPS
gps:
  satellites:
    id: num_sat

time:
  - platform: gps
    id: gpstime
    timezone: Europe/Berlin

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 24
  - file: "gfonts://Roboto"
    id: font2
    size: 18

i2c:
  sda: 20
  scl: 21
  scan: false

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.strftime(0, 0, id(font1), "%H:%M", id(gpstime).now());
      it.printf(0, 31, id(font2), "Satellites: %1.0f", id(num_sat).state);

ota:
  platform: esphome
  password: !secret ota_password

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
