esphome:
  name: wemos1

esp32:
  board: lolin32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# run webserver
web_server:
  port: 80
  local: true

# set i2c ports
i2c:
  sda: 4
  scl: 5

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 60s

# font:
#   # gfonts://family[@weight]
#   - file: "gfonts://Roboto"
#     id: roboto
#     size: 10

# display:
#   - platform: ssd1306_i2c
#     model: "SSD1306 128x64"
#     address: 0x3C
#     lambda: |-
#       it.print(0, 0, id(roboto), "Hello World!");

